### PR TITLE
Allow for using emails with top domain as .online

### PR DESCRIPTION
**Pull request by kkszysiu**
Could you please review, merge and build a new version?

It's a change to support email validation for emails like: test@test.online for example.

Thanks!

### CODE REVIEW

**Comment by bodbdigr** [comment]
@kkszysiu it seems that some tests are failing after this change https://travis-ci.org/bodbdigr/restea/builds/211380129, other then that I have no complains. thank you!

**Comment by kkszysiu** [comment]
@bodbdigr done :)

**Comment by bodbdigr** [comment]
@kkszysiu done, thank you!

**Comment by kkszysiu** [comment]
Thank you @bodbdigr  🍺 👍

**Pull request merged**
